In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("ClasificacionEuro.xlsx")
rank = pd.read_excel("RankingFifa.xlsx")


In [3]:
#### correct data types

In [4]:
df

Date         Country       home_team  home_score  away_score  \
0   2023-03-25         Escocia         Escocia           3           0   
1   2023-03-25          España          España           3           0   
2   2023-03-28         Georgia         Georgia           1           1   
3   2023-03-28         Escocia         Escocia           2           0   
4   2023-06-17         Noruega         Noruega           1           2   
..         ...             ...             ...         ...         ...   
239 2023-09-12        Alemania        Alemania           2           1   
240 2023-10-14  Estados Unidos  Estados Unidos           3           1   
241 2023-10-18          México          México           2           2   
242 2023-11-18        Alemania        Alemania           2           3   
243 2023-11-21         Austria         Austria           0           2   

    away_team  
0      Chipre  
1     Noruega  
2     Noruega  
3      España  
4     Escocia  
..        ...  
239   Francia  
240  Alemania  
241  Alemania  
242   Turquía  
243  Alemania  

[244 rows x 6 columns]

In [5]:
rank

Ranking              País  Jugadores en la plantilla  edad  Valor total  \
0       1           Argentina                         29  28.0       865.70   
1       2             Francia                         25  26.9      1200.00   
2       4          Inglaterra                         33  25.8      1700.00   
3       3             Bélgica                         25  26.9       591.00   
4       5              Brasil                         26  25.6      1200.00   
..      ...               ...                        ...   ...          ...   
191   204           Sri Lanka                         24  26.6         1.93   
192   205                Guam                         25  24.9         1.00   
193   206     Turcas y Caicos                         17  20.8         0.00   
194   208         Vírgenes A.                         17  24.0         0.00   
195   210          San Marino                         23  24.9         1.00   

    Confederación  Puntos  
0        CONMEBOL    1858  
1            UEFA    1841  
2            UEFA    1795  
3            UEFA    1795  
4        CONMEBOL    1789  
..            ...     ...  
191           AFC     829  
192           AFC     822  
193      CONCACAF     817  
194      CONCACAF     797  
195          UEFA     742  

[196 rows x 7 columns]

In [6]:
df['Date']


0     2023-03-25
1     2023-03-25
2     2023-03-28
3     2023-03-28
4     2023-06-17
         ...    
239   2023-09-12
240   2023-10-14
241   2023-10-18
242   2023-11-18
243   2023-11-21
Name: Date, Length: 244, dtype: datetime64[ns]

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

In [8]:
relevant_info = ["País", "Puntos", "Ranking", "Valor total"]

In [9]:
print(df["home_team"].dtype)
print(rank["País"].dtype)

object
object


In [10]:
df["home_team"] = df["home_team"].astype(str)
rank["País"] = rank["País"].astype(str)

In [11]:
rank["País"] = rank["País"].str.replace('\xa0', '', regex=False)


In [12]:
print(rank["País"].unique())

['Argentina' 'Francia' 'Inglaterra' 'Bélgica' 'Brasil' 'Portugal'
 'Países Bajos' 'España' 'Italia' 'Croacia' 'Estados Unidos' 'Colombia'
 'Marruecos' 'México' 'Uruguay' 'Alemania' 'Senegal' 'Japón' 'Suiza'
 'Irán' 'Dinamarca' 'Ucrania' 'Corea del Sur' 'Australia' 'Austria'
 'Suecia' 'Hungría' 'Polonia' 'Gales' 'Nigeria' 'Ecuador' 'Perú' 'Serbia'
 'Catar' 'Rusia' 'República Checa' 'Egipto' 'Costa de Marfil' 'Escocia'
 'Turquía' 'Túnez' 'Chile' 'Argelia' 'Malí' 'Panamá' 'Noruega' 'Rumania'
 'Eslovaquia' 'Canadá' 'Grecia' 'Camerún' 'Costa Rica' 'Arabia Saudita'
 'Venezuela' 'Jamaica' 'Paraguay' 'Eslovenia' 'Irak' 'Sudáfrica' 'Irlanda'
 'Finlandia' 'Burkina Faso' 'RD Congo' 'Uzbekistán' 'Cabo Verde' 'Albania'
 'E. Á. U.' 'Ghana' 'Macedonia Norte' 'Montenegro' 'Jordania' 'Islandia'
 'Irlanda Norte' 'Bosnia' 'Georgia' 'Guinea' 'Omán' 'Israel'
 'Guinea Ecuat.' 'Baréin' 'El Salvador' 'Honduras' 'Bulgaria' 'Gabón'
 'Bolivia' 'Zambia' 'Luxemburgo' 'China' 'Siria' 'Curazao' 'Haití'
 'Uganda' 'Pa

In [13]:
df_euro=df.merge(rank[relevant_info], left_on = ["home_team"], right_on = ["País"]).drop(['País'], axis = 1)

In [14]:
df_euro

Date         Country       home_team  home_score  away_score  \
0   2023-03-25         Escocia         Escocia           3           0   
1   2023-03-28         Escocia         Escocia           2           0   
2   2023-06-20         Escocia         Escocia           2           0   
3   2023-11-19         Escocia         Escocia           3           3   
4   2023-03-25          España          España           3           0   
..         ...             ...             ...         ...         ...   
225 2023-09-09        Alemania        Alemania           1           4   
226 2023-09-12        Alemania        Alemania           2           1   
227 2023-11-18        Alemania        Alemania           2           3   
228 2023-10-14  Estados Unidos  Estados Unidos           3           1   
229 2023-10-18          México          México           2           2   

    away_team  Puntos Ranking  Valor total  
0      Chipre    1497    39         214.35  
1      España    1497    39         214.35  
2     Georgia    1497    39         214.35  
3     Noruega    1497    39         214.35  
4     Noruega    1728     8        1000.00  
..        ...     ...     ...          ...  
225     Japón    1644    16         898.00  
226   Francia    1644    16         898.00  
227   Turquía    1644    16         898.00  
228  Alemania    1681    11         323.80  
229  Alemania    1661    14         208.30  

[230 rows x 9 columns]

In [15]:
df_euro.merge(rank[relevant_info], left_on = ["away_team"], right_on = ["País"],suffixes = ('_home', '_away')).drop(['País'], axis = 1)

Date     Country   home_team  home_score  away_score away_team  \
0   2023-03-25     Escocia     Escocia           3           0    Chipre   
1   2023-09-12      España      España           6           0    Chipre   
2   2023-10-15     Georgia     Georgia           4           0    Chipre   
3   2023-06-20     Noruega     Noruega           3           1    Chipre   
4   2023-03-28     Escocia     Escocia           2           0    España   
..         ...         ...         ...         ...         ...       ...   
210 2023-03-26  Luxemburgo  Luxemburgo           0           6  Portugal   
211 2023-06-20    Islandia    Islandia           0           1  Portugal   
212 2023-03-25    Alemania    Alemania           2           0      Perú   
213 2023-06-20    Alemania    Alemania           0           2  Colombia   
214 2023-09-09    Alemania    Alemania           1           4     Japón   

     Puntos_home Ranking_home  Valor total_home  Puntos_away Ranking_away  \
0           1497         39              214.35         1141        124     
1           1728          8             1000.00         1141        124     
2           1334         75              153.40         1141        124     
3           1468         47              491.40         1141        124     
4           1497         39              214.35         1728          8     
..           ...          ...               ...          ...          ...   
210         1278         87               14.83         1748          6     
211         1347         72               70.75         1748          6     
212         1644         16              898.00         1516         32     
213         1644         16              898.00         1664         12     
214         1644         16              898.00         1622         18     

     Valor total_away  
0               17.65  
1               17.65  
2               17.65  
3               17.65  
4             1000.00  
..                ...  
210           1000.00  
211           1000.00  
212             30.65  
213            278.60  
214            231.40  

[215 rows x 12 columns]

In [16]:
df_euro= df_euro.merge(rank[relevant_info], left_on = ["away_team"], right_on = ["País"],suffixes = ('_home', '_away')).drop(['País'], axis = 1)

In [17]:
## Target Definition

In [18]:
df_euro["home_score"] = df_euro["home_score"].astype(int)

In [19]:
df_euro["away_score"] = df_euro["away_score"].astype(int)

In [20]:
df_euro.loc[df_euro['home_score'] > df_euro['away_score'], 'target'] = 1
df_euro.loc[df_euro['home_score'] == df_euro['away_score'], 'target'] = 2
df_euro.loc[df_euro['home_score'] < df_euro['away_score'], 'target'] = 3

In [21]:
## Feature engineering

In [22]:
df_euro['Ranking_home'] = df_euro['Ranking_home'].astype(int)


In [23]:
df_euro['Ranking_away'] = df_euro['Ranking_away'].astype(int)


In [24]:
#rank difference
df_euro['rank_dif'] = df_euro ['Ranking_home'] - df_euro['Ranking_away']

In [25]:
df_euro

Date     Country   home_team  home_score  away_score away_team  \
0   2023-03-25     Escocia     Escocia           3           0    Chipre   
1   2023-09-12      España      España           6           0    Chipre   
2   2023-10-15     Georgia     Georgia           4           0    Chipre   
3   2023-06-20     Noruega     Noruega           3           1    Chipre   
4   2023-03-28     Escocia     Escocia           2           0    España   
..         ...         ...         ...         ...         ...       ...   
210 2023-03-26  Luxemburgo  Luxemburgo           0           6  Portugal   
211 2023-06-20    Islandia    Islandia           0           1  Portugal   
212 2023-03-25    Alemania    Alemania           2           0      Perú   
213 2023-06-20    Alemania    Alemania           0           2  Colombia   
214 2023-09-09    Alemania    Alemania           1           4     Japón   

     Puntos_home  Ranking_home  Valor total_home  Puntos_away  Ranking_away  \
0           1497            39            214.35         1141           124   
1           1728             8           1000.00         1141           124   
2           1334            75            153.40         1141           124   
3           1468            47            491.40         1141           124   
4           1497            39            214.35         1728             8   
..           ...           ...               ...          ...           ...   
210         1278            87             14.83         1748             6   
211         1347            72             70.75         1748             6   
212         1644            16            898.00         1516            32   
213         1644            16            898.00         1664            12   
214         1644            16            898.00         1622            18   

     Valor total_away  target  rank_dif  
0               17.65     1.0       -85  
1               17.65     1.0      -116  
2               17.65     1.0       -49  
3               17.65     1.0       -77  
4             1000.00     1.0        31  
..                ...     ...       ...  
210           1000.00     3.0        81  
211           1000.00     3.0        66  
212             30.65     1.0       -16  
213            278.60     3.0         4  
214            231.40     3.0        -2  

[215 rows x 14 columns]

In [26]:
# racha de goles

##df_euro.sort_values(['home_team', 'Date'], inplace = True)

In [27]:
##df_euro ['racha_home_1'] = df_euro.groupby(['home_team'])['home_score'].shift(1)

In [28]:
##Final clean up

In [29]:
df_euro.columns

Index(['Date', 'Country', 'home_team', 'home_score', 'away_score', 'away_team',
       'Puntos_home', 'Ranking_home', 'Valor total_home', 'Puntos_away',
       'Ranking_away', 'Valor total_away', 'target', 'rank_dif'],
      dtype='object')

In [30]:
variables_finales = ['home_team', 'away_team', 'Puntos_home', 'Ranking_home', 'Valor total_home', 'Puntos_away',
       'Ranking_away', 'Valor total_away', 'target', 'rank_dif',
       ]

In [31]:
df_final= df_euro [variables_finales]

In [32]:
df_final

home_team away_team  Puntos_home  Ranking_home  Valor total_home  \
0       Escocia    Chipre         1497            39            214.35   
1        España    Chipre         1728             8           1000.00   
2       Georgia    Chipre         1334            75            153.40   
3       Noruega    Chipre         1468            47            491.40   
4       Escocia    España         1497            39            214.35   
..          ...       ...          ...           ...               ...   
210  Luxemburgo  Portugal         1278            87             14.83   
211    Islandia  Portugal         1347            72             70.75   
212    Alemania      Perú         1644            16            898.00   
213    Alemania  Colombia         1644            16            898.00   
214    Alemania     Japón         1644            16            898.00   

     Puntos_away  Ranking_away  Valor total_away  target  rank_dif  
0           1141           124             17.65     1.0       -85  
1           1141           124             17.65     1.0      -116  
2           1141           124             17.65     1.0       -49  
3           1141           124             17.65     1.0       -77  
4           1728             8           1000.00     1.0        31  
..           ...           ...               ...     ...       ...  
210         1748             6           1000.00     3.0        81  
211         1748             6           1000.00     3.0        66  
212         1516            32             30.65     1.0       -16  
213         1664            12            278.60     3.0         4  
214         1622            18            231.40     3.0        -2  

[215 rows x 10 columns]

In [33]:
df_enconde_home = pd.get_dummies(df_final['home_team'], prefix = '_home')

In [34]:
df_enconde_away = pd.get_dummies(df_final['away_team'], prefix = '_away')

In [35]:
df_final= pd.concat([df_final,df_enconde_home], axis = 1)

In [36]:
df_final= pd.concat([df_final,df_enconde_away], axis = 1)

In [37]:
df_final

home_team away_team  Puntos_home  Ranking_home  Valor total_home  \
0       Escocia    Chipre         1497            39            214.35   
1        España    Chipre         1728             8           1000.00   
2       Georgia    Chipre         1334            75            153.40   
3       Noruega    Chipre         1468            47            491.40   
4       Escocia    España         1497            39            214.35   
..          ...       ...          ...           ...               ...   
210  Luxemburgo  Portugal         1278            87             14.83   
211    Islandia  Portugal         1347            72             70.75   
212    Alemania      Perú         1644            16            898.00   
213    Alemania  Colombia         1644            16            898.00   
214    Alemania     Japón         1644            16            898.00   

     Puntos_away  Ranking_away  Valor total_away  target  rank_dif  ...  \
0           1141           124             17.65     1.0       -85  ...   
1           1141           124             17.65     1.0      -116  ...   
2           1141           124             17.65     1.0       -49  ...   
3           1141           124             17.65     1.0       -77  ...   
4           1728             8           1000.00     1.0        31  ...   
..           ...           ...               ...     ...       ...  ...   
210         1748             6           1000.00     3.0        81  ...   
211         1748             6           1000.00     3.0        66  ...   
212         1516            32             30.65     1.0       -16  ...   
213         1664            12            278.60     3.0         4  ...   
214         1622            18            231.40     3.0        -2  ...   

     _away_Polonia  _away_Portugal  _away_República Checa  _away_Rumania  \
0                0               0                      0              0   
1                0               0                      0              0   
2                0               0                      0              0   
3                0               0                      0              0   
4                0               0                      0              0   
..             ...             ...                    ...            ...   
210              0               1                      0              0   
211              0               1                      0              0   
212              0               0                      0              0   
213              0               0                      0              0   
214              0               0                      0              0   

     _away_San Marino  _away_Serbia  _away_Suecia  _away_Suiza  _away_Turquía  \
0                   0             0             0            0              0   
1                   0             0             0            0              0   
2                   0             0             0            0              0   
3                   0             0             0            0              0   
4                   0             0             0            0              0   
..                ...           ...           ...          ...            ...   
210                 0             0             0            0              0   
211                 0             0             0            0              0   
212                 0             0             0            0              0   
213                 0             0             0            0              0   
214                 0             0             0            0              0   

     _away_Ucrania  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
210              0  
211              0  
212              0  
213              0  
214              0  

[215 rows x 117 columns]

In [38]:
df_final.drop(['home_team', 'away_team'], axis = 1, inplace = True)

In [39]:
df_final

Puntos_home  Ranking_home  Valor total_home  Puntos_away  Ranking_away  \
0           1497            39            214.35         1141           124   
1           1728             8           1000.00         1141           124   
2           1334            75            153.40         1141           124   
3           1468            47            491.40         1141           124   
4           1497            39            214.35         1728             8   
..           ...           ...               ...          ...           ...   
210         1278            87             14.83         1748             6   
211         1347            72             70.75         1748             6   
212         1644            16            898.00         1516            32   
213         1644            16            898.00         1664            12   
214         1644            16            898.00         1622            18   

     Valor total_away  target  rank_dif  _home_Albania  _home_Alemania  ...  \
0               17.65     1.0       -85              0               0  ...   
1               17.65     1.0      -116              0               0  ...   
2               17.65     1.0       -49              0               0  ...   
3               17.65     1.0       -77              0               0  ...   
4             1000.00     1.0        31              0               0  ...   
..                ...     ...       ...            ...             ...  ...   
210           1000.00     3.0        81              0               0  ...   
211           1000.00     3.0        66              0               0  ...   
212             30.65     1.0       -16              0               1  ...   
213            278.60     3.0         4              0               1  ...   
214            231.40     3.0        -2              0               1  ...   

     _away_Polonia  _away_Portugal  _away_República Checa  _away_Rumania  \
0                0               0                      0              0   
1                0               0                      0              0   
2                0               0                      0              0   
3                0               0                      0              0   
4                0               0                      0              0   
..             ...             ...                    ...            ...   
210              0               1                      0              0   
211              0               1                      0              0   
212              0               0                      0              0   
213              0               0                      0              0   
214              0               0                      0              0   

     _away_San Marino  _away_Serbia  _away_Suecia  _away_Suiza  _away_Turquía  \
0                   0             0             0            0              0   
1                   0             0             0            0              0   
2                   0             0             0            0              0   
3                   0             0             0            0              0   
4                   0             0             0            0              0   
..                ...           ...           ...          ...            ...   
210                 0             0             0            0              0   
211                 0             0             0            0              0   
212                 0             0             0            0              0   
213                 0             0             0            0              0   
214                 0             0             0            0              0   

     _away_Ucrania  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
210              0  
211              0  
212              0  
213        

In [40]:
df_final.dropna(inplace=True)

In [41]:
### Modelizacion

In [42]:
y = df_final[['target']]

In [43]:
y

target
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
..      ...
210     3.0
211     3.0
212     1.0
213     3.0
214     3.0

[215 rows x 1 columns]

In [44]:
x = df_final.drop('target', axis=1)

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [48]:
model = RandomForestClassifier(random_state = 5, max_depth = 9, n_estimators = 100)

In [49]:
model.fit(x_train, y_train)

C:\Users\mmandelman\AppData\Local\Temp\ipykernel_14116\940050797.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train, y_train)


RandomForestClassifier(max_depth=9, random_state=5)

In [50]:
## predicciones

In [51]:
model.predict(x_test)

array([1., 3., 3., 3., 3., 2., 3., 3., 1., 2., 1., 1., 3., 1., 2., 3., 3.,
       3., 2., 2., 1., 3., 3., 2., 3., 3., 1., 1., 3., 1., 1., 1., 3., 1.,
       1., 1., 3., 3., 1., 3., 1., 1., 2.])

In [52]:
y_test_pred = pd.DataFrame(model.predict(x_test), index = y_test.index, columns =['predicciones'])

In [53]:
pred = pd.concat([y_test, y_test_pred], axis = 1)

In [54]:
pred['Exito'] = (pred['target'] == pred['predicciones']).astype(int)

In [55]:
pred['Exito'].mean()

0.5581395348837209

In [56]:
## Predicciones Euro

In [57]:
## variables_finales = ['Puntos_home', 'Ranking_home', 'Valor total_home', 'Puntos_away','Ranking_away', 'Valor total_away', 'rank_dif']

In [58]:
## GRUPO A: Alemania, Escocia, Suiza, Hungría

In [59]:
game_Alemania_Escocia = [1644, 16, 898, 1497, 39, 214, -23]

from itertools import repeat
game_Alemania_Escocia=game_Alemania_Escocia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Alemania_Escocia], columns = x_test.columns)

euro_pred['_home_Alemania'] = 1

euro_pred['_away_Escocia'] = 1

model.predict_proba(euro_pred)

array([[0.39762283, 0.28649298, 0.31588419]])

In [60]:
game_Hungria_Suiza = [1532, 26, 165, 1616, 19, 302, 7]

from itertools import repeat
game_Hungria_Suiza=game_Hungria_Suiza + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Hungria_Suiza], columns = x_test.columns)

euro_pred['_home_Hungría'] = 1

euro_pred['_away_Suiza'] = 1

model.predict_proba(euro_pred)

array([[0.43064417, 0.17929959, 0.39005624]])

In [61]:
game_Escocia_Suiza = [1497, 39, 214, 1616, 19, 302, 20]

from itertools import repeat
game_Escocia_Suiza=game_Escocia_Suiza + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Escocia_Suiza], columns = x_test.columns)

euro_pred['_home_Escocia'] = 1

euro_pred['_away_Suiza'] = 1

model.predict_proba(euro_pred)

array([[0.36640152, 0.2490135 , 0.38458498]])

In [62]:
game_Alemania_Hungria = [1644, 16, 898, 1532, 26, 165, -10]

from itertools import repeat
game_Alemania_Hungria=game_Alemania_Hungria + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Alemania_Hungria], columns = x_test.columns)

euro_pred['_home_Alemania'] = 1

euro_pred['_away_Hungría'] = 1

model.predict_proba(euro_pred)

array([[0.34212704, 0.43030889, 0.22756407]])

In [63]:
game_Suiza_Alemania = [1532, 26, 165, 1644, 16, 898, 10]

from itertools import repeat
game_Suiza_Alemania=game_Suiza_Alemania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Suiza_Alemania], columns = x_test.columns)

euro_pred['_home_Suiza'] = 1

euro_pred['_away_Alemania'] = 1

model.predict_proba(euro_pred)

array([[0.19146418, 0.24590958, 0.56262623]])

In [64]:
game_Escocia_Hungria = [1497, 39, 214, 1532, 26, 165, 13]

from itertools import repeat
game_Escocia_Hungria=game_Escocia_Hungria + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Escocia_Hungria], columns = x_test.columns)

euro_pred['_home_Escocia'] = 1

euro_pred['_away_Hungría'] = 1

model.predict_proba(euro_pred)

array([[0.34486268, 0.41603267, 0.23910465]])

In [65]:
##CLASIFICADOS: 1- Alemania, 2- Suiza

In [66]:
## GRUPO B: España, Croacia, Italia, Albania

In [67]:
game_España_Croacia = [1728, 8, 1000, 1721, 10, 332, -2]

from itertools import repeat
game_España_Croacia=game_España_Croacia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_España_Croacia], columns = x_test.columns)

euro_pred['_home_España'] = 1

euro_pred['_away_Croacia'] = 1

model.predict_proba(euro_pred)

array([[0.61713377, 0.08029154, 0.30257469]])

In [68]:
game_España_Italia = [1728, 8, 1000, 1725, 9, 754, -1]

from itertools import repeat
game_España_Italia=game_España_Italia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_España_Italia], columns = x_test.columns)

euro_pred['_home_España'] = 1

euro_pred['_away_Italia'] = 1

model.predict_proba(euro_pred)

array([[0.63430344, 0.07158162, 0.29411494]])

In [69]:
game_Croacia_Albania = [1721, 10, 332, 1375, 66, 111, -56]

from itertools import repeat
game_Croacia_Albania=game_Croacia_Albania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Croacia_Albania], columns = x_test.columns)

euro_pred['_home_Croacia'] = 1

euro_pred['_away_Albania'] = 1

model.predict_proba(euro_pred)

array([[0.69382107, 0.2300635 , 0.07611543]])

In [70]:
game_Croacia_Italia = [1721, 10, 332, 1725, 9, 754, 1]

from itertools import repeat
game_Croacia_Italia=game_Croacia_Italia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Croacia_Italia], columns = x_test.columns)

euro_pred['_home_Croacia'] = 1

euro_pred['_away_Italia'] = 1

model.predict_proba(euro_pred)

array([[0.36447143, 0.18720791, 0.44832066]])

In [71]:
game_Albania_España = [ 1375, 66, 111, 1728, 8, 1000, 58]

from itertools import repeat
game_Albania_España=game_Albania_España + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Albania_España], columns = x_test.columns)

euro_pred['_home_Albania'] = 1

euro_pred['_away_España'] = 1

model.predict_proba(euro_pred)

array([[0.22892456, 0.13300574, 0.6380697 ]])

In [72]:
game_Italia_Albania = [1725, 9, 754, 1375, 66, 111, -57]

from itertools import repeat
game_Italia_Albania=game_Italia_Albania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Italia_Albania], columns = x_test.columns)

euro_pred['_home_Italia'] = 1

euro_pred['_away_Albania'] = 1

model.predict_proba(euro_pred)

array([[0.76717104, 0.14269984, 0.09012913]])

In [73]:
##CLASIFICADOS: 1- Esp, 2- Ita

In [74]:
## GRUPO C: Eslovenia, Dinamarca, Serbia, Inglaterra

In [75]:
game_Eslovenia_Dinamarca = [1428, 57, 149, 1603, 21, 420, 36]

from itertools import repeat
game_Eslovenia_Dinamarca=game_Eslovenia_Dinamarca + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Eslovenia_Dinamarca], columns = x_test.columns)

euro_pred['_home_Eslovenia'] = 1

euro_pred['_away_Dinamarca'] = 1

model.predict_proba(euro_pred)

array([[0.22308861, 0.38384011, 0.39307128]])

In [76]:
game_Serbia_Inglaterra = [1514, 33, 318,1795, 4, 1700, 29]

from itertools import repeat
game_Serbia_Inglaterra=game_Serbia_Inglaterra + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Serbia_Inglaterra], columns = x_test.columns)

euro_pred['_home_Serbia'] = 1

euro_pred['_away_Inglaterra'] = 1

model.predict_proba(euro_pred)

array([[0.09016082, 0.39998846, 0.50985072]])

In [77]:
game_Eslovenia_Serbia = [1428, 57, 149, 1375, 66, 111, -9]

from itertools import repeat
game_Eslovenia_Serbia=game_Eslovenia_Serbia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Eslovenia_Serbia], columns = x_test.columns)

euro_pred['_home_Eslovenia'] = 1

euro_pred['_away_Serbia'] = 1

model.predict_proba(euro_pred)

array([[0.56139091, 0.28719982, 0.15140928]])

In [78]:
game_Dinamarca_Inglaterra = [1603, 21, 420, 1795, 4, 1700, 17]

from itertools import repeat
game_Dinamarca_Inglaterra=game_Dinamarca_Inglaterra + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Dinamarca_Inglaterra], columns = x_test.columns)

euro_pred['_home_Dinamarca'] = 1

euro_pred['_away_Inglaterra'] = 1

model.predict_proba(euro_pred)

array([[0.1359084 , 0.37083655, 0.49325505]])

In [79]:
game_Dinamarca_Serbia = [1603, 21, 420, 1375, 66, 111, -15]

from itertools import repeat
game_Dinamarca_Serbia=game_Dinamarca_Serbia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Dinamarca_Serbia], columns = x_test.columns)

euro_pred['_home_Dinamarca'] = 1

euro_pred['_away_Serbia'] = 1

model.predict_proba(euro_pred)

array([[0.67895333, 0.21902534, 0.10202133]])

In [80]:
game_Inglaterra_Eslovenia = [1795, 4, 1700, 1428, 57, 149, 53]

from itertools import repeat
game_Inglaterra_Eslovenia=game_Inglaterra_Eslovenia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Inglaterra_Eslovenia], columns = x_test.columns)

euro_pred['_home_Inglaterra'] = 1

euro_pred['_away_Eslovenia'] = 1

model.predict_proba(euro_pred)

array([[0.58898247, 0.17567214, 0.23534539]])

In [81]:
##CLASIFICADOS: 1- Ing, 2- Din

In [82]:
## GRUPO D: Polonia, Países Bajos, Austria y Francia.

In [83]:
game_Polonia_Paises = [1531, 28, 218, 1742, 7, 835, 21]

from itertools import repeat
game_Polonia_Paises=game_Polonia_Paises + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Polonia_Paises], columns = x_test.columns)

euro_pred['_home_Polonia'] = 1

euro_pred['_away_Países Bajos'] = 1

model.predict_proba(euro_pred)

array([[0.1529229 , 0.13267026, 0.71440684]])

In [84]:
game_Austria_Francia = [1555, 25, 245, 1841, 2, 1200, 23]

from itertools import repeat
game_Austria_Francia=game_Austria_Francia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Austria_Francia], columns = x_test.columns)

euro_pred['_home_Austria'] = 1

euro_pred['_away_Francia'] = 1

model.predict_proba(euro_pred)

array([[0.13037099, 0.30469092, 0.56493809]])

In [85]:
game_Paises_Francia = [1742, 7, 835, 1841, 2, 1200, 5]

from itertools import repeat
game_Paises_Francia=game_Paises_Francia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Paises_Francia], columns = x_test.columns)

euro_pred['_away_Países Bajos'] = 1

euro_pred['_away_Francia'] = 1

model.predict_proba(euro_pred)

array([[0.16072339, 0.16014321, 0.67913341]])

In [86]:
game_Polonia_Austria = [1531, 28, 218, 1555, 25, 245, 3]

from itertools import repeat
game_Polonia_Austria=game_Polonia_Austria + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Polonia_Austria], columns = x_test.columns)

euro_pred['_home_Polonia'] = 1

euro_pred['_away_Austria'] = 1

model.predict_proba(euro_pred)

array([[0.27332678, 0.23725629, 0.48941692]])

In [87]:
game_Francia_Polonia = [1841, 2, 1200, 1531, 28, 218, -26]

from itertools import repeat
game_Francia_Polonia=game_Francia_Polonia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Francia_Polonia], columns = x_test.columns)

euro_pred['_home_Francia'] = 1

euro_pred['_away_Polonia'] = 1

model.predict_proba(euro_pred)

array([[0.6973833 , 0.21861839, 0.08399831]])

In [88]:
game_Paises_Austria = [1742, 7, 835, 1555, 25, 245, -18]

from itertools import repeat
game_Paises_Austria=game_Paises_Austria + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Paises_Austria], columns = x_test.columns)

euro_pred['_away_Países Bajos'] = 1

euro_pred['_away_Austria'] = 1

model.predict_proba(euro_pred)

array([[0.47079755, 0.3209995 , 0.20820296]])

In [89]:
##CLASIFICADOS: 1- Fra, 2- Países Bajos

In [90]:
## GRUPO E: Bélgica, Eslovaquia, Rumania y Ucrania.

In [91]:
game_Bélgica_Eslovaquia = [1795, 3, 591, 1462, 48, 169, -45]

from itertools import repeat
game_Bélgica_Eslovaquia=game_Bélgica_Eslovaquia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Bélgica_Eslovaquia], columns = x_test.columns)

euro_pred['_home_Bélgica'] = 1

euro_pred['_away_Eslovaquia'] = 1

model.predict_proba(euro_pred)

array([[0.57400488, 0.34074723, 0.08524789]])

In [92]:
game_Rumania_Ucrania = [1468, 46, 91, 1569, 22, 345, 24]

from itertools import repeat
game_Rumania_Ucrania=game_Rumania_Ucrania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Rumania_Ucrania], columns = x_test.columns)

euro_pred['_home_Rumania'] = 1

euro_pred['_away_Ucrania'] = 1

model.predict_proba(euro_pred)

array([[0.46587676, 0.20868538, 0.32543786]])

In [93]:
game_Eslovaquia_Ucrania = [1462, 48, 169, 1569, 22, 345, 26]

from itertools import repeat
game_Eslovaquia_Ucrania=game_Eslovaquia_Ucrania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Eslovaquia_Ucrania], columns = x_test.columns)

euro_pred['_home_Eslovaquia'] = 1

euro_pred['_away_Ucrania'] = 1

model.predict_proba(euro_pred)

array([[0.34781699, 0.2566204 , 0.39556262]])

In [94]:
game_Bélgica_Rumania = [1795, 3, 591, 1468, 46, 91, -43]

from itertools import repeat
game_Bélgica_Rumania=game_Bélgica_Rumania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Bélgica_Rumania], columns = x_test.columns)

euro_pred['_home_Bélgica'] = 1

euro_pred['_away_Rumania'] = 1

model.predict_proba(euro_pred)

array([[0.48014283, 0.44504843, 0.07480874]])

In [95]:
game_Ucrania_Bélgica = [1569, 22, 345, 1795, 3, 591, 19]

from itertools import repeat
game_Ucrania_Bélgica=game_Ucrania_Bélgica + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Ucrania_Bélgica], columns = x_test.columns)

euro_pred['_home_Ucrania'] = 1

euro_pred['_away_Bélgica'] = 1

model.predict_proba(euro_pred)

array([[0.0593331 , 0.19515121, 0.74551569]])

In [96]:
game_Eslovaquia_Rumania = [1462, 48, 169, 1468, 46, 91, -43]

from itertools import repeat
game_Eslovaquia_Rumania=game_Eslovaquia_Rumania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Eslovaquia_Rumania], columns = x_test.columns)

euro_pred['_home_Eslovaquia'] = 1

euro_pred['_away_Rumania'] = 1

model.predict_proba(euro_pred)

array([[0.44026792, 0.42387711, 0.13585497]])

In [97]:
##CLASIFICADOS: 1- Bel, 2- Rum

In [98]:
## GRUPO F: Turquía, Georgia, Portugal y República Checa.

In [99]:
game_Turquía_Georgia = [1496, 40, 368, 1334, 75, 153, -35]

from itertools import repeat
game_Turquía_Georgia=game_Turquía_Georgia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Turquía_Georgia], columns = x_test.columns)

euro_pred['_home_Turquía'] = 1

euro_pred['_away_Georgia'] = 1

model.predict_proba(euro_pred)

array([[0.60721971, 0.31474122, 0.07803907]])

In [100]:
game_Portugal_RepúblicaCheca = [1748, 6, 1000, 1501, 36, 176, -30]

from itertools import repeat
game_Portugal_RepúblicaCheca=game_Portugal_RepúblicaCheca + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Portugal_RepúblicaCheca], columns = x_test.columns)

euro_pred['_home_Portugal'] = 1

euro_pred['_away_República Checa'] = 1

model.predict_proba(euro_pred)

array([[0.67954601, 0.2458216 , 0.0746324 ]])

In [101]:
game_Georgia_RepúblicaCheca = [1334, 75, 153, 1501, 36, 176, 39]

from itertools import repeat
game_Georgia_RepúblicaCheca=game_Georgia_RepúblicaCheca + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Georgia_RepúblicaCheca], columns = x_test.columns)

euro_pred['_home_Georgia'] = 1

euro_pred['_away_República Checa'] = 1

model.predict_proba(euro_pred)

array([[0.16401345, 0.56691156, 0.26907499]])

In [102]:
game_Turquía_Portugal = [1496, 40, 368, 1748, 6, 1000, 34]

from itertools import repeat
game_Turquía_Portugal=game_Turquía_Portugal + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Turquía_Portugal], columns = x_test.columns)

euro_pred['_home_Turquía'] = 1

euro_pred['_away_Portugal'] = 1

model.predict_proba(euro_pred)

array([[0.08250179, 0.13542828, 0.78206992]])

In [103]:
game_Georgia_Portugal = [1334, 75, 153, 1748, 6, 1000, 69]

from itertools import repeat
game_Georgia_Portugal=game_Georgia_Portugal + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Georgia_Portugal], columns = x_test.columns)

euro_pred['_home_Georgia'] = 1

euro_pred['_away_Portugal'] = 1

model.predict_proba(euro_pred)

array([[0.04822879, 0.20724767, 0.74452354]])

In [104]:
game_RepúblicaCheca_Turquía = [1501, 36, 176, 1496, 40, 368, -4]

from itertools import repeat
game_RepúblicaCheca_Turquía=game_RepúblicaCheca_Turquía + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_RepúblicaCheca_Turquía], columns = x_test.columns)

euro_pred['_home_República Checa'] = 1

euro_pred['_away_Turquía'] = 1

model.predict_proba(euro_pred)

array([[0.4161748 , 0.30704293, 0.27678227]])

In [105]:
##CLASIFICADOS: 1- Port, 2- Turq

In [106]:
##Plays OFFs:
##


##alemania- dina
##españa - 3
##
##portugal-3
##países bajos -rumania
##
##suiza - italia
##Inglaterra -3
##
##belgica - 3
##franc - turquia

In [107]:
game_Alemania_Dinamarca = [1644, 16, 898, 1603, 21, 420, -5]

from itertools import repeat
game_Alemania_Dinamarca=game_Alemania_Dinamarca + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Alemania_Dinamarca], columns = x_test.columns)

euro_pred['_home_Alemania'] = 1

euro_pred['_away_Dinamarca'] = 1

model.predict_proba(euro_pred)

array([[0.33401546, 0.33490814, 0.3310764 ]])

In [108]:
game_PaísesBajos_rumania = [1742, 7, 835, 1468, 46, 91, -39]

from itertools import repeat
game_PaísesBajos_rumania=game_PaísesBajos_rumania + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_PaísesBajos_rumania], columns = x_test.columns)

euro_pred['_home_Países Bajos'] = 1

euro_pred['_away_Rumania'] = 1

model.predict_proba(euro_pred)

array([[0.63349317, 0.25913104, 0.10737579]])

In [109]:
game_Suiza_Italia = [1532, 26, 165, 1725, 9, 754, 17]

from itertools import repeat
game_Suiza_Italia=game_Suiza_Italia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Suiza_Italia], columns = x_test.columns)

euro_pred['_home_Suiza'] = 1

euro_pred['_away_Italia'] = 1

model.predict_proba(euro_pred)

array([[0.21863363, 0.23288145, 0.54848492]])

In [110]:
game_Francia_Turquía = [1841, 2, 1200, 1496, 40, 368, -38]

from itertools import repeat
game_Francia_Turquía=game_Francia_Turquía + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Francia_Turquía], columns = x_test.columns)

euro_pred['_home_Francia'] = 1

euro_pred['_away_Turquía'] = 1

model.predict_proba(euro_pred)

array([[0.64678729, 0.1260789 , 0.22713381]])

In [111]:
##Cuartos de final

In [112]:

game_Alemania_España = [1644, 16, 898, 1728, 8, 1000, 8]

from itertools import repeat
game_Alemania_España=game_Alemania_España + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Alemania_España], columns = x_test.columns)

euro_pred['_home_Alemania'] = 1

euro_pred['_away_España'] = 1

model.predict_proba(euro_pred)

array([[0.1256682 , 0.12941404, 0.74491776]])

In [114]:

game_PaísesBajos_Portugal = [1742, 7, 835, 1748, 6, 1000, 1]

from itertools import repeat
game_PaísesBajos_Portugal=game_PaísesBajos_Portugal + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_PaísesBajos_Portugal], columns = x_test.columns)

euro_pred['_home_Países Bajos'] = 1

euro_pred['_away_Portugal'] = 1

model.predict_proba(euro_pred)

array([[0.27011777, 0.08366901, 0.64621322]])

In [115]:

game_Italia_Inglaterra = [1725, 9, 754, 1795, 4, 1700, 5]

from itertools import repeat
game_Italia_Inglaterra=game_Italia_Inglaterra + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Italia_Inglaterra], columns = x_test.columns)

euro_pred['_home_Italia'] = 1

euro_pred['_away_Inglaterra'] = 1

model.predict_proba(euro_pred)

array([[0.18008562, 0.20791317, 0.61200121]])

In [116]:
game_Belgica_Francia = [1795, 3, 591, 1841, 2, 1200, 1]

from itertools import repeat
game_Belgica_Francia=game_Belgica_Francia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Belgica_Francia], columns = x_test.columns)

euro_pred['_home_Bélgica'] = 1

euro_pred['_away_Francia'] = 1

model.predict_proba(euro_pred)

array([[0.2152107 , 0.27699965, 0.50778965]])

In [117]:
##Semifinales España

In [119]:
game_Alemania_Portugal = [1728, 8, 1000, 1748, 6, 1000, 2]

#SEMI-FINAL 1:

from itertools import repeat
game_Alemania_Portugal=game_Germany_Portugal + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Germany_Portugal], columns = x_test.columns)

euro_pred['_home_Alemania'] = 1

euro_pred['_away_Portugal'] = 1

model.predict_proba(euro_pred)

array([[0.26949207, 0.06195135, 0.66855659]])

In [125]:
game_England_France = [1795, 4, 1700, 1841, 2, 1200, 2]

#SEMI-FINAL 2:

from itertools import repeat
game_England_France=game_England_France + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_England_France], columns = x_test.columns)

euro_pred['_home_Inglaterra'] = 1

euro_pred['_away_Francia'] = 1

model.predict_proba(euro_pred)

array([[0.36978034, 0.12166542, 0.50855424]])

In [121]:
##Final

In [126]:
game_Portugal_Francia = [1748, 6, 1000, 1841, 2, 1200, 4]

from itertools import repeat
game_Portugal_Francia=game_Portugal_Francia + list(repeat(0,107))

euro_pred = pd.DataFrame ([game_Portugal_Francia], columns = x_test.columns)

euro_pred['_home_Portugal'] = 1

euro_pred['_away_Francia'] = 1

model.predict_proba(euro_pred)

array([[0.265854  , 0.1279082 , 0.60623781]])